"""PDF Report Generator for Machine Maintenance Logs"""

from fpdf import FPDF
from datetime import datetime
import io


class MachinePDFReport(FPDF):
    """Custom PDF class with header and footer"""

    def __init__(self, machine_id):
        super().__init__()
        self.machine_id = machine_id
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        # Blue bar
        self.set_fill_color(31, 119, 180)
        self.rect(0, 0, 210, 18, 'F')
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 4)
        self.cell(0, 10, f"PlantPulse AI  |  Machine Report: {self.machine_id}", ln=False)
        self.set_text_color(0, 0, 0)
        self.ln(18)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8,
                  f"Generated by PlantPulse AI  |  {datetime.now().strftime('%Y-%m-%d %H:%M')}  |  Page {self.page_no()}",
                  align="C")
        self.set_text_color(0, 0, 0)


# ── Colour helpers ────────────────────────────────────────────────────────────

def _risk_color(level):
    return {
        "Critical": (214, 39, 40),
        "High":     (255, 127, 14),
        "Medium":   (255, 187, 120),
        "Low":      (44, 160, 44),
    }.get(level, (100, 100, 100))


def _section_title(pdf, title):
    pdf.set_fill_color(240, 242, 246)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(31, 119, 180)
    pdf.cell(0, 8, f"  {title}", ln=True, fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)


def _kv(pdf, label, value, bold_value=False):
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(52, 6, label + ":", ln=False)
    pdf.set_font("Helvetica", "B" if bold_value else "", 9)
    pdf.cell(0, 6, _safe(str(value)), ln=True)


def _bullet(pdf, text, indent=8):
    pdf.set_font("Helvetica", "", 9)
    pdf.set_x(10)
    pdf.multi_cell(190, 5, f"  - {_safe(text)}")


def _safe(text):
    """Strip characters that latin-1 can't encode"""
    return str(text).encode("latin-1", errors="replace").decode("latin-1")


# ── Main export function ──────────────────────────────────────────────────────

def generate_machine_pdf(machine_id, machine_logs_df, risk_info,
                          repair_recommendation, failure_window,
                          ml_result=None):
    """
    Generate a complete PDF report for one machine.

    Parameters
    ----------
    machine_id          : str
    machine_logs_df     : pd.DataFrame  – filtered logs for this machine
    risk_info           : dict          – from failure_predictor.calculate_risk_score()
    repair_recommendation: dict         – from repair_recommender.get_repair_recommendation()
    failure_window      : dict          – from failure_predictor.predict_failure_window()
    ml_result           : dict | None   – ML anomaly result (optional)

    Returns
    -------
    bytes  – raw PDF bytes ready for st.download_button
    """
    import pandas as pd

    pdf = MachinePDFReport(machine_id)
    pdf.add_page()

    risk_level = risk_info.get("risk_level", "Unknown")
    risk_score = risk_info.get("risk_score", 0)
    rc, gc, bc = _risk_color(risk_level)

    # ── 1. MACHINE SUMMARY ────────────────────────────────────────────────────
    _section_title(pdf, "1. Machine Summary")

    # Risk badge
    pdf.set_fill_color(rc, gc, bc)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(60, 10, f"  {risk_level.upper()}  ({risk_score}/100)", fill=True, ln=False)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(12)

    total_incidents = len(machine_logs_df)
    total_downtime  = int(machine_logs_df["downtime_minutes"].sum()) if total_incidents else 0
    temp_fixes      = len(machine_logs_df[machine_logs_df["action_taken"] == "temporary_fix"]) if total_incidents else 0
    prod_line       = machine_logs_df.iloc[0]["production_line"] if total_incidents else "N/A"

    _kv(pdf, "Machine ID",       machine_id)
    _kv(pdf, "Production Line",  prod_line)
    _kv(pdf, "Total Incidents",  total_incidents)
    _kv(pdf, "Total Downtime",   f"{total_downtime} minutes")
    _kv(pdf, "Temporary Fixes",  temp_fixes)
    _kv(pdf, "Predicted Failure",failure_window.get("predicted_window", "N/A"), bold_value=True)
    _kv(pdf, "Report Date",      datetime.now().strftime("%Y-%m-%d %H:%M"))
    pdf.ln(4)

    # ── 2. RISK FACTORS ───────────────────────────────────────────────────────
    _section_title(pdf, "2. Risk Factors")
    factors = risk_info.get("factors", [])
    if factors:
        for f in factors:
            _bullet(pdf, f)
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 6, "  No significant risk factors detected.", ln=True)
    pdf.ln(4)

    # ── 3. ML ANOMALY DETECTION ───────────────────────────────────────────────
    _section_title(pdf, "3. ML Anomaly Detection")
    ml_anomaly    = risk_info.get("ml_anomaly", False)
    ml_confidence = risk_info.get("ml_confidence", 0)

    if ml_anomaly:
        pdf.set_fill_color(255, 220, 220)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, _safe(f"  ANOMALY DETECTED  --  Confidence: {ml_confidence}%"), fill=True, ln=True)
    else:
        pdf.set_fill_color(220, 255, 220)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, "  Normal Behaviour  --  No anomaly detected", fill=True, ln=True)

    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # ── 4. REPAIR RECOMMENDATION ──────────────────────────────────────────────
    _section_title(pdf, "4. Repair Recommendation")

    _kv(pdf, "Issue Type",        repair_recommendation.get("issue_type", "N/A"))
    _kv(pdf, "Primary Component", repair_recommendation.get("primary_component", "N/A"), bold_value=True)
    _kv(pdf, "All Components",    ", ".join(repair_recommendation.get("all_components", [])))
    _kv(pdf, "Estimated Cost",    f"Rs. {repair_recommendation.get('estimated_cost_inr', 0):,}")
    _kv(pdf, "Estimated Time",    f"{repair_recommendation.get('estimated_time_hours', 0)} hours")
    _kv(pdf, "Urgency",           repair_recommendation.get("urgency", "N/A"))
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, "Temporary Fix:", ln=True)
    _bullet(pdf, repair_recommendation.get("temporary_fix", "N/A"))

    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, "Permanent Fix:", ln=True)
    _bullet(pdf, repair_recommendation.get("permanent_fix", "N/A"))
    pdf.ln(4)

    # ── 5. TOOLS & SAFETY ─────────────────────────────────────────────────────
    _section_title(pdf, "5. Tools Required & Safety Precautions")

    col_w = 90
    x_start = pdf.get_x()
    y_start = pdf.get_y()

    # Tools column
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(col_w, 6, "Tools Required:", ln=False)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, "Safety Precautions:", ln=True)

    tools      = repair_recommendation.get("tools_required", [])
    precautions= repair_recommendation.get("safety_precautions", [])
    rows = max(len(tools), len(precautions))

    for i in range(rows):
        pdf.set_font("Helvetica", "", 9)
        t = f"- {_safe(tools[i])}"       if i < len(tools)       else ""
        s = f"- {_safe(precautions[i])}" if i < len(precautions) else ""
        pdf.cell(col_w, 5, t, ln=False)
        pdf.cell(0,     5, s, ln=True)

    pdf.ln(4)

    # ── 6. YOUTUBE TUTORIALS ──────────────────────────────────────────────────
    _section_title(pdf, "6. Repair Tutorial Videos")
    for i, video in enumerate(repair_recommendation.get("youtube_videos", []), 1):
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 5, f"  Video {i}: {_safe(video['title'])}", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, f"    Duration: {video['duration']}  |  Views: {video['views']}", ln=True)
        pdf.set_text_color(31, 119, 180)
        pdf.cell(0, 5, f"    URL: {video['url']}", ln=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(1)
    pdf.ln(3)

    # ── 7. ISSUE BREAKDOWN ────────────────────────────────────────────────────
    _section_title(pdf, "7. Issue Type Breakdown")
    if total_incidents:
        issue_counts = machine_logs_df["issue_type"].value_counts()
        # Table header
        pdf.set_fill_color(31, 119, 180)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(80, 7, "Issue Type",    fill=True, border=1, ln=False)
        pdf.cell(30, 7, "Count",         fill=True, border=1, ln=False)
        pdf.cell(40, 7, "% of Total",    fill=True, border=1, ln=True)
        pdf.set_text_color(0, 0, 0)

        for issue, count in issue_counts.items():
            pct = f"{count / total_incidents * 100:.1f}%"
            fill = (245, 245, 245) if list(issue_counts.index).index(issue) % 2 == 0 else (255, 255, 255)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_fill_color(*fill)
            pdf.cell(80, 6, f"  {_safe(issue.replace('_', ' ').title())}", fill=True, border=1, ln=False)
            pdf.cell(30, 6, str(count),                                     fill=True, border=1, ln=False)
            pdf.cell(40, 6, pct,                                             fill=True, border=1, ln=True)
    pdf.ln(4)

    # ── 8. MAINTENANCE LOG HISTORY ────────────────────────────────────────────
    pdf.add_page()
    _section_title(pdf, "8. Complete Maintenance Log History")

    if total_incidents:
        logs_sorted = machine_logs_df.sort_values("date", ascending=False)

        # Table header
        pdf.set_fill_color(31, 119, 180)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(28, 7, "Date",          fill=True, border=1, ln=False)
        pdf.cell(28, 7, "Issue Type",    fill=True, border=1, ln=False)
        pdf.cell(28, 7, "Action Taken",  fill=True, border=1, ln=False)
        pdf.cell(18, 7, "Downtime",      fill=True, border=1, ln=False)
        pdf.cell(20, 7, "Criticality",   fill=True, border=1, ln=False)
        pdf.cell(0,  7, "Technician Note",fill=True, border=1, ln=True)
        pdf.set_text_color(0, 0, 0)

        for idx, (_, row) in enumerate(logs_sorted.iterrows()):
            try:
                date_str = pd.to_datetime(row["date"]).strftime("%Y-%m-%d")
            except Exception:
                date_str = str(row["date"])[:10]

            issue    = _safe(str(row.get("issue_type", "")).replace("_", " ").title()[:18])
            action   = _safe(str(row.get("action_taken", "")).replace("_", " ").title()[:18])
            downtime = str(int(row.get("downtime_minutes", 0))) + " min"
            crit     = _safe(str(row.get("criticality", ""))[:10])
            note     = _safe(str(row.get("technician_note", ""))[:55])
            if len(str(row.get("technician_note", ""))) > 55:
                note += "..."

            fill_color = (245, 245, 245) if idx % 2 == 0 else (255, 255, 255)
            pdf.set_fill_color(*fill_color)

            # Criticality colour dot
            crit_color = _risk_color(crit)

            pdf.set_font("Helvetica", "", 7)
            pdf.cell(28, 5, date_str, fill=True, border=1, ln=False)
            pdf.cell(28, 5, issue,    fill=True, border=1, ln=False)
            pdf.cell(28, 5, action,   fill=True, border=1, ln=False)
            pdf.cell(18, 5, downtime, fill=True, border=1, ln=False)

            # Colour-coded criticality
            pdf.set_fill_color(*crit_color)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(20, 5, crit, fill=True, border=1, ln=False)
            pdf.set_text_color(0, 0, 0)
            pdf.set_fill_color(*fill_color)

            pdf.cell(0, 5, note, fill=True, border=1, ln=True)
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 6, "  No logs found for this machine.", ln=True)

    pdf.ln(4)

    # ── 9. SUMMARY & NEXT STEPS ───────────────────────────────────────────────
    _section_title(pdf, "9. Summary & Recommended Next Steps")

    steps = [
        f"1. Predicted failure window: {failure_window.get('predicted_window', 'N/A')} — act before this deadline.",
        f"2. Replace / repair: {repair_recommendation.get('primary_component', 'N/A')}",
        f"3. Estimated repair cost: Rs. {repair_recommendation.get('estimated_cost_inr', 0):,}",
        f"4. Estimated repair time: {repair_recommendation.get('estimated_time_hours', 0)} hours",
        f"5. {repair_recommendation.get('permanent_fix', 'Perform permanent fix')}",
        "6. After repair: update maintenance log and re-run risk analysis.",
        "7. Schedule follow-up inspection in 7 days to confirm resolution.",
    ]
    for step in steps:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_x(10)
        pdf.multi_cell(190, 5, f"  {_safe(step)}")
        pdf.ln(1)

    # Return bytes
    return bytes(pdf.output())
